### ISSUE TITLE
support for sbt 0.11.3?

### ISSUE THREAD

**Issue by garrettux** [twitter-archive/sbt-package-dist#4]
Hi, do you plan on having this plugin support sbt 0.11.3?  Right now I get an unresolved dependency error running "sbt clean update" because it's looking in http://maven.twttr.com/com/twitter/sbt-package-dist_2.9.1_0.11.3 but right now the repo is http://maven.twttr.com/com/twitter/sbt-package-dist_2.9.1_0.11.2.  Thanks!

**Comment by caniszczyk** [comment]
Any thoughts on this @zuercher ?

**Comment by ryanking** [comment]
We've mostly moved away from sbt, so don't expect much support.

**Comment by garrettux** [comment]
Fair enough.  Thanks for the quick response!
